
package com.centit.gk.msasoa;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2018-06-15T15:28:32.118+08:00
 * Generated source version: 2.7.6
 * 
 */
public final class BlackRedSOAP_BlackRedSOAPImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://msasoa.gk.centit.com/", "BlackRedSOAPImplService");

    private BlackRedSOAP_BlackRedSOAPImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BlackRedSOAPImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BlackRedSOAPImplService ss = new BlackRedSOAPImplService(wsdlURL, SERVICE_NAME);
        BlackRedSOAP port = ss.getBlackRedSOAPImplPort();  
        
        {
        System.out.println("Invoking getRedBlackType...");
        java.lang.String _getRedBlackType_sysId = "";
        java.lang.String _getRedBlackType_loginname = "";
        java.lang.String _getRedBlackType_personname = "";
        java.lang.String _getRedBlackType_departmentname = "";
        java.lang.String _getRedBlackType_unitedType = "";
        java.lang.String _getRedBlackType__return = port.getRedBlackType(_getRedBlackType_sysId, _getRedBlackType_loginname, _getRedBlackType_personname, _getRedBlackType_departmentname, _getRedBlackType_unitedType);
        System.out.println("getRedBlackType.result=" + _getRedBlackType__return);


        }
        {
        System.out.println("Invoking getRedBlackBack...");
        java.lang.String _getRedBlackBack_sysId = "";
        java.lang.String _getRedBlackBack_loginname = "";
        java.lang.String _getRedBlackBack_personname = "";
        java.lang.String _getRedBlackBack_departmentname = "";
        java.lang.String _getRedBlackBack_startTime = "";
        java.lang.String _getRedBlackBack_endTime = "";
        java.lang.String _getRedBlackBack_feedbackType = "";
        java.lang.String _getRedBlackBack_unitedType = "";
        java.lang.String _getRedBlackBack_param = "";
        long _getRedBlackBack_page = 0;
        long _getRedBlackBack_size = 0;
        java.lang.String _getRedBlackBack__return = port.getRedBlackBack(_getRedBlackBack_sysId, _getRedBlackBack_loginname, _getRedBlackBack_personname, _getRedBlackBack_departmentname, _getRedBlackBack_startTime, _getRedBlackBack_endTime, _getRedBlackBack_feedbackType, _getRedBlackBack_unitedType, _getRedBlackBack_param, _getRedBlackBack_page, _getRedBlackBack_size);
        System.out.println("getRedBlackBack.result=" + _getRedBlackBack__return);


        }
        {
        System.out.println("Invoking commitRedBlackBack...");
        java.lang.String _commitRedBlackBack_sysId = "";
        java.lang.String _commitRedBlackBack_loginname = "";
        java.lang.String _commitRedBlackBack_personname = "";
        java.lang.String _commitRedBlackBack_departmentname = "";
        com.centit.gk.msasoa.BlackRedBackRequest _commitRedBlackBack_redblackBackList = null;
        java.lang.String _commitRedBlackBack__return = port.commitRedBlackBack(_commitRedBlackBack_sysId, _commitRedBlackBack_loginname, _commitRedBlackBack_personname, _commitRedBlackBack_departmentname, _commitRedBlackBack_redblackBackList);
        System.out.println("commitRedBlackBack.result=" + _commitRedBlackBack__return);


        }
        {
        System.out.println("Invoking getRedBlackPage...");
        java.lang.String _getRedBlackPage_sysId = "";
        java.lang.String _getRedBlackPage_loginname = "";
        java.lang.String _getRedBlackPage_personname = "";
        java.lang.String _getRedBlackPage_departmentname = "";
        java.lang.String _getRedBlackPage_param = "";
        java.lang.String _getRedBlackPage_redList = "";
        java.lang.String _getRedBlackPage_blackList = "";
        java.lang.String _getRedBlackPage__return = port.getRedBlackPage(_getRedBlackPage_sysId, _getRedBlackPage_loginname, _getRedBlackPage_personname, _getRedBlackPage_departmentname, _getRedBlackPage_param, _getRedBlackPage_redList, _getRedBlackPage_blackList);
        System.out.println("getRedBlackPage.result=" + _getRedBlackPage__return);


        }

        System.exit(0);
    }

}
