package com.centit.gk.msasoa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2018-06-15T15:28:32.180+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "BlackRedSOAPImplService", 
                  wsdlLocation = "http://10.224.5.9:7800/cqxyfw/blackredinfo/SOAP?wsdl",
                  targetNamespace = "http://msasoa.gk.centit.com/") 
public class BlackRedSOAPImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://msasoa.gk.centit.com/", "BlackRedSOAPImplService");
    public final static QName BlackRedSOAPImplPort = new QName("http://msasoa.gk.centit.com/", "BlackRedSOAPImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.224.5.9:7800/cqxyfw/blackredinfo/SOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BlackRedSOAPImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.224.5.9:7800/cqxyfw/blackredinfo/SOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BlackRedSOAPImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BlackRedSOAPImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BlackRedSOAPImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BlackRedSOAPImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BlackRedSOAPImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BlackRedSOAPImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BlackRedSOAP
     */
    @WebEndpoint(name = "BlackRedSOAPImplPort")
    public BlackRedSOAP getBlackRedSOAPImplPort() {
        return super.getPort(BlackRedSOAPImplPort, BlackRedSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BlackRedSOAP
     */
    @WebEndpoint(name = "BlackRedSOAPImplPort")
    public BlackRedSOAP getBlackRedSOAPImplPort(WebServiceFeature... features) {
        return super.getPort(BlackRedSOAPImplPort, BlackRedSOAP.class, features);
    }

}
