package com.centit.gk.msasoa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2018-06-15T15:28:32.180+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://msasoa.gk.centit.com/", name = "BlackRedSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface BlackRedSOAP {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRedBlackType", targetNamespace = "http://msasoa.gk.centit.com/", className = "com.centit.gk.msasoa.GetRedBlackType")
    @WebMethod
    @ResponseWrapper(localName = "getRedBlackTypeResponse", targetNamespace = "http://msasoa.gk.centit.com/", className = "com.centit.gk.msasoa.GetRedBlackTypeResponse")
    public java.lang.String getRedBlackType(
        @WebParam(name = "sysId", targetNamespace = "")
        java.lang.String sysId,
        @WebParam(name = "loginname", targetNamespace = "")
        java.lang.String loginname,
        @WebParam(name = "personname", targetNamespace = "")
        java.lang.String personname,
        @WebParam(name = "departmentname", targetNamespace = "")
        java.lang.String departmentname,
        @WebParam(name = "unitedType", targetNamespace = "")
        java.lang.String unitedType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRedBlackBack", targetNamespace = "http://msasoa.gk.centit.com/", className = "com.centit.gk.msasoa.GetRedBlackBack")
    @WebMethod
    @ResponseWrapper(localName = "getRedBlackBackResponse", targetNamespace = "http://msasoa.gk.centit.com/", className = "com.centit.gk.msasoa.GetRedBlackBackResponse")
    public java.lang.String getRedBlackBack(
        @WebParam(name = "sysId", targetNamespace = "")
        java.lang.String sysId,
        @WebParam(name = "loginname", targetNamespace = "")
        java.lang.String loginname,
        @WebParam(name = "personname", targetNamespace = "")
        java.lang.String personname,
        @WebParam(name = "departmentname", targetNamespace = "")
        java.lang.String departmentname,
        @WebParam(name = "startTime", targetNamespace = "")
        java.lang.String startTime,
        @WebParam(name = "endTime", targetNamespace = "")
        java.lang.String endTime,
        @WebParam(name = "feedbackType", targetNamespace = "")
        java.lang.String feedbackType,
        @WebParam(name = "unitedType", targetNamespace = "")
        java.lang.String unitedType,
        @WebParam(name = "param", targetNamespace = "")
        java.lang.String param,
        @WebParam(name = "page", targetNamespace = "")
        long page,
        @WebParam(name = "size", targetNamespace = "")
        long size
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "commitRedBlackBack", targetNamespace = "http://msasoa.gk.centit.com/", className = "com.centit.gk.msasoa.CommitRedBlackBack")
    @WebMethod
    @ResponseWrapper(localName = "commitRedBlackBackResponse", targetNamespace = "http://msasoa.gk.centit.com/", className = "com.centit.gk.msasoa.CommitRedBlackBackResponse")
    public java.lang.String commitRedBlackBack(
        @WebParam(name = "sysId", targetNamespace = "")
        java.lang.String sysId,
        @WebParam(name = "loginname", targetNamespace = "")
        java.lang.String loginname,
        @WebParam(name = "personname", targetNamespace = "")
        java.lang.String personname,
        @WebParam(name = "departmentname", targetNamespace = "")
        java.lang.String departmentname,
        @WebParam(name = "redblackBackList", targetNamespace = "")
        com.centit.gk.msasoa.BlackRedBackRequest redblackBackList
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRedBlackPage", targetNamespace = "http://msasoa.gk.centit.com/", className = "com.centit.gk.msasoa.GetRedBlackPage")
    @WebMethod
    @ResponseWrapper(localName = "getRedBlackPageResponse", targetNamespace = "http://msasoa.gk.centit.com/", className = "com.centit.gk.msasoa.GetRedBlackPageResponse")
    public java.lang.String getRedBlackPage(
        @WebParam(name = "sysId", targetNamespace = "")
        java.lang.String sysId,
        @WebParam(name = "loginname", targetNamespace = "")
        java.lang.String loginname,
        @WebParam(name = "personname", targetNamespace = "")
        java.lang.String personname,
        @WebParam(name = "departmentname", targetNamespace = "")
        java.lang.String departmentname,
        @WebParam(name = "param", targetNamespace = "")
        java.lang.String param,
        @WebParam(name = "redList", targetNamespace = "")
        java.lang.String redList,
        @WebParam(name = "blackList", targetNamespace = "")
        java.lang.String blackList
    );
}
